title: Hao Sun 
subtitle: ML, NLP, TTS
description: >- # this means to ignore newlines until "baseurl:"
  website

url: "https://sigmeta.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about.html
    - text: Contact Me
      url : /contact.html
    - text: Styleguide
      url: /styleguide.html
    

# Edit these details 

author_logo: profile.png
author: Hao Sun
author_bio: Hi, My Name is Hao Sun. I love machine learning and NLP.
author_email: "sigmeta@pku.edu.com"
author_location: Beijing, China
author_website_url: "http://sigmeta.github.io"

author_work_experiences: 
            - company_name: Microsoft STCA
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Bing SDE
              description: NLP
              visibility: true
            - company_name: Microsoft MSRA
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Research Intern
              description: NLP, TTS
              visibility: true

author_education_details:
              - college_logo: pku.jpg
                college_name: Peking University
                college_url: https://www.pku.edu.cn
                college_degree: Software Engineering
                description: Master of Technology
                visibility: true
              - college_logo: tju.jpg
                college_name: Tianjin University
                college_url: https://www.tju.edu.cn
                college_degree: Communication Engineering
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: interspeech.jpg
                project_title: Interspeech 2019
                project_description: Token-Level Ensemble Distillation for Grapheme-to-Phoneme Conversion
                project_url: https://arxiv.org/abs/1904.03446v1
                visibility: true
              - project_thumbnail: asru.jpg
                project_title: ASRU 2019
                project_description: Knowledge Distillation from BERT in Pre-training and Fine-tuning for Polyphone Disambiguation
                project_url: #
                visibility: true

# social links
github_username:  sigmeta
linkedin_username: 豪-孙-0694aa141
twitter_username: /
facebook_username: /
behance_username: /
instagram_username: /
medium_username: /
telegram_username: /
dribbble_username: /
flickr_username: /

#for comments using disqus
disqus_shortname: 

# wakatime username (coding activity)
wakatime_username: sigmeta

# formspree (contact form)
formspree_email: sigmeta@pku.edu.cn

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics:  

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/